### ISSUE TITLE
Simplification problem

### ISSUE THREAD

**Issue by rbuchmann** [clojure-numerics/expresso#15]
Hi,

thanks for expresso, it's awesome!
I am writing a library to compile collections of definitions into fast functions using expresso, e.g.
(compute f7 (= f0 0) (= f0 1) (= fn (+ fn-1 fn-2))).
I have to do a lot of substituting and simplification before generating the final expression, and I ran into a weird error:

```clojure
(c/simplify (c/substitute '(= b (* a 3)) {'a '(+ 5 6)}))  ;; =>ClassCastException clojure.lang.Symbol cannot be cast to java.lang.Number  clojure.lang.Numbers.multiply (Numbers.java:146)

(c/simplify (= b (* (+ 5 6) 3))) ;; => works fine
```

Otherwise, working with it has just been a pleasure!

**Comment by mschuene** [comment]
I am glad you find expresso useful. 
I am looking into it. Quick fix is that 
(c/simplify (c/substitute '(= b (* a 3)) {'a (ex (+ 5 6))}))
works fine

normally expresso's api is designed so that one doesn't has to call ex or other expression constructing functions manually and that they are called when needed upon api entry

**Comment by mschuene** [comment]
it actually makes sense that one has to call ex explicitly when one substitutes a variable. 
core.matrix also accepts sequences to the operators and so will expresso:

numeric.expresso.core> (simplify (substitute '(* a b) {'a '(1 2 3) 'b '(4 5 6)}))
[4 10 18]

**Comment by rbuchmann** [comment]
Hm, I find that part a little confusing. I would prefer if I didn't have to think about what parts need an extra call to ex and what parts don't. In this example, it should be clear that the substituted expression isn't a vector or a sequence, or am I missing something?

**Comment by mschuene** [comment]
there are no guarantees in core.matrix about admissible scalar types for matrices, so '(x y z) could be a valid matrix. For example there is a proof of concept symbolic matrix implementation. 

To differentiate between these situations one would have to check if the input is a list, its first element is a symbol and if it resolves to a function. But this also can fail when one uses expressions purely for symbolic manipulation because then the names don't have to resolve to a clojure function.

You don't have to use the ex macro for conversion, but you can have everything in normal quoted lists and then call constr/to-expression  when building the substitution map.

**Comment by rbuchmann** [comment]
I see, that actually makes a lot of sense. Thanks for the clarification, I will just incorporate the call into my substition map builder like you suggested.
